D:\PythonProject\Time_series_anomaly_detection\weights\2022_02_04 21_27_09
series:  0      29.9
1      30.6
2      24.8
3      37.2
4      21.0
       ...
304    41.7
305    35.3
306     0.0
307    39.8
308    41.9
Name: concentration, Length: 309, dtype: float64
D:\PythonProject\Time_series_anomaly_detection\utils\data_prepare.py:17: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ..\torch\csrc\utils\tensor_new.cpp:201.)
  return torch.FloatTensor(inout_seq)
-----------------------------------------------------------------------------------------
| end of epoch   1 | time:  1.82s | valid loss 0.54508
-----------------------------------------------------------------------------------------
save successfully
-----------------------------------------------------------------------------------------
| end of epoch   2 | time:  1.71s | valid loss 0.11256
-----------------------------------------------------------------------------------------
save successfully
-----------------------------------------------------------------------------------------
| end of epoch   3 | time:  1.70s | valid loss 0.03928
-----------------------------------------------------------------------------------------
save successfully
-----------------------------------------------------------------------------------------
| end of epoch   4 | time:  1.70s | valid loss 0.08992
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   5 | time:  1.76s | valid loss 0.15683
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   6 | time:  1.72s | valid loss 0.06377
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   7 | time:  1.76s | valid loss 0.04589
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   8 | time:  1.77s | valid loss 0.04657
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   9 | time:  1.78s | valid loss 0.03177
-----------------------------------------------------------------------------------------
save successfully
loss shape:  torch.Size([307])
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main(args)
  File "train.py", line 98, in main
    val_loss = plot_and_loss(model, val_data, epoch, criterion, input_window, timestamp)
  File "D:\PythonProject\Time_series_anomaly_detection\utils\plot_and_loss.py", line 39, in plot_and_loss
    res = pd.DataFrame({"date": timestamp.values, "truth": truth, "test_result": test_result, "loss": test_result - truth})
  File "D:\miniconda\envs\pytorch\lib\site-packages\pandas\core\frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "D:\miniconda\envs\pytorch\lib\site-packages\pandas\core\internals\construction.py", line 465, in dict_to_mgr
    arrays, data_names, index, columns, dtype=dtype, typ=typ, consolidate=copy
  File "D:\miniconda\envs\pytorch\lib\site-packages\pandas\core\internals\construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "D:\miniconda\envs\pytorch\lib\site-packages\pandas\core\internals\construction.py", line 635, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length